# Generated by Django 3.0.1 on 2019-12-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metta_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='name',
        ),
    ]
