# Generated by Django 3.0.1 on 2019-12-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metta_forum', '0002_auto_20191219_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
