# Generated by Django 3.0.2 on 2020-01-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200103_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='date_added',
        ),
    ]
